With Prices AS (
	-- 篩選床位的部分是為了顯示成人的價錢, 以免小孩的因素影響整體
  SELECT TRSUBD.GRUP_CD,
	COALESCE(MIN(CASE WHEN CURR_AM > 0 THEN CURR_AM END),0) AS DIRECT_CUSTOMER_PRICE, 
    COALESCE(MIN(CASE WHEN AGT_AM > 0 THEN AGT_AM END),0) AS B2B_MEM_PRICE,
    COALESCE(MIN(CASE WHEN PRD_AM3 > 0 THEN PRD_AM3 END),0) AS B2C_MEM_PRICE,
    COALESCE(MIN(CASE WHEN PRD_AM4 > 0 THEN PRD_AM4 END),0) AS AGT_PRICE,
    COALESCE(MIN(CASE WHEN PRD_AM5 > 0 THEN PRD_AM5 END),0) AS ENTERPRISE_PRICE
  FROM TRSUBD
  WHERE BED_TP NOT BETWEEN 2 AND 5 AND JOIN_TP=1
  GROUP BY GRUP_CD
  )

SELECT * FROM Prices