With Pax_histories AS (
	SELECT 
		PAX_CD, 
		COUNT(*) AS ATTENDING_TIMES,
		COUNT(CASE WHEN tp.TLDR_FG = TRUE THEN 1 END) AS TL_TIMES,
		SUM(GAR_AM) AS GAR_AM

	FROM TRGPAX tp
	WHERE CAST(GRUP_ST AS INTEGER) BETWEEN 1 AND 4 AND PAX_CD IS NOT NULL AND PAX_CD <> ''
	GROUP BY PAX_CD
)

select * from Pax_histories